### ISSUE TITLE
pip install os-sys error

### ISSUE THREAD

**Issue by techhalloman** [MyNameJeremy/EzEb#1]
Hi.. i used UbuntuStudio 

ERROR: os-sys has an invalid wheel, could not read 'os_sys-1.9.3.dist-info/WHEEL' file: KeyError("There is no item named 'os_sys-1.9.3.dist-info/WHEEL' in the archive")

one frame working 

lastly 

Click the "Run All" button . missing

**Comment by jeremyssocial** [comment]
Sorry, EzEb only works on windows for now.

**Comment by JocelynVelarde** [comment]
import os
import sys

It should also work that way^

**Comment by Professorwired** [comment]
how we can resolve this error???????

**Comment by sarvesh2847** [comment]
Same error, is there any alternative solution possibe??

**Comment by WasiiBukhari2** [comment]
Solution of this error please

**Comment by jeremyssocial** [comment]
should be working after the latest update 👍

I removed os-sys because it doesn't seem to be a valid python package
